force exit code 0 on clean procedure

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -104,9 +104,9 @@ echo "publish ${PROJECT_FILE}"
 dotnet build $PROJECT_FILE --output /$BUILD_DIR/release --configuration Release --runtime linux-x64
 dotnet publish $PROJECT_FILE --output /$BUILD_DIR/release --configuration Release --runtime linux-x64
 
-echo "Remove all files and folders except Procfile and Release folder"
+echo "Remove all files and folders except Procfile and Release folder ignoring errors"
 cd $BUILD_DIR
-find -maxdepth 1 ! -name Procfile ! -name release -delete
+find -maxdepth 1 ! -name Procfile ! -name release -delete || true
 
 cat << EOT >> ${BUILD_DIR}/Procfile
 web: cd \$HOME/release && ASPNETCORE_URLS='http://+:\$PORT' && /app/newrelic/usr/local/newrelic-netcore20-agent/run.sh dotnet "./${PROJECT_NAME}.dll"
